var h=null;global.MicrodataJS={};MicrodataJS.getItemValue=function(b){var c=b.nodeName;return b.getAttribute("itemscope")!==h?b:c==="META"?b.content:~"AUDIO,EMBED,IFRAME,IMG,SOURCE,VIDEO".split(",").indexOf(c)?b.src:~["A","AREA","LINK"].indexOf(c)?b.href:c==="OBJECT"?b.data:c==="TIME"&&b.getAttribute("datetime")?b.dateTime:"textContent"in b?b.textContent:b.innerText};
MicrodataJS.setItemValue=function(b,c){var f=b.nodeName,g="innerHTML";f==="META"?g="content":"AUDIO,EMBED,IFRAME,IMG,SOURCE,VIDEO".split(",").indexOf(f)!==-1?g="src":["A","AREA","LINK"].indexOf(f)!==-1?g="href":f==="OBJECT"?g="data":f==="TIME"&&b.getAttribute("datetime")&&(g="dateTime");return b[g]=c};
(!document.getItems?function(b,c,f){function g(a){var b=[],c=[],e=new i,n=[];f(a.childNodes).forEach(function(a){a.nodeType===1&&b.push(a)});a.getAttribute("itemref")&&(n=a.getAttribute("itemref").trim().split(/\s+/),n.forEach(function(a){(a=document.getElementById(a))&&b.push(a)}));b=b.filter(function(a,c){var e=h,g=a,f=[];if(b.indexOf(a)!==c&&b.indexOf(a,c)!==-1)return!1;for(;(g=g.parentNode)!==h&&g.nodeType===1;)if(f.push(g),g.getAttribute("itemscope")!==h){e=g;break}return e!==h?b.indexOf(e)!==
-1?!1:!f.some(function(a){var c=-1,j=h;if((c=b.indexOf(a))!==-1){for(a=b[c];(a=a.parentNode)!==h&&a.nodeType===1;)if(a.getAttribute("itemscope")!==h){j=a;break}if(j===e)return!0}return!1}):!0});for(b.sort(function(a,b){return 3-((b.compareDocumentPosition?b.compareDocumentPosition(a):b.contains?(b!=a&&b.contains(a)&&16)+(b!=a&&a.contains(b)&&8)+(b.sourceIndex>=0&&a.sourceIndex>=0?(b.sourceIndex<a.sourceIndex&&4)+(b.sourceIndex>a.sourceIndex&&2):1)+0:0)&6)});a=b.pop();){if(a.getAttribute("itemprop")&&
(c.push(a),a.getAttribute("itemscope")!==h))a.itemScope=!0,a.properties=g(a);a.getAttribute("itemscope")===h&&(a=f(a.childNodes).reverse(),a.forEach(function(a){a.nodeType===1&&b.push(a)}))}c.forEach(function(a){var b=a.getAttribute("itemprop").split(" "),c=m.getItemValue(a);a.itemValue=c;(a.itemProp=b).forEach(e.a.bind(e,a,c))});return e}var m=b.MicrodataJS;m.fixItemElement=function(a){var b;a.itemScope=!0;a.properties=g(a);if(b=a.getAttribute("itemid"))a.itemId=b;if(b=a.getAttribute("itemref"))a.itemRef=
b;if(b=a.getAttribute("itemtype"))a.itemType=b;return a};if(!b.PropertyNodeList){var e=b.PropertyNodeList=function(){this.length=0;this.values=[]};e.prototype.a=function(a,b){this[this.length++]=a;this.values.push(b)};e.prototype.namedItem=function(){};e.prototype.getValues=function(){return this.values};e.prototype.toString=function(){return"[object PropertyNodeList]"}}if(!b.HTMLPropertiesCollection){var i=b.HTMLPropertiesCollection=function(){this.length=0;this.names=[]};i.prototype.a=function(a,
b,c){this[this.length++]=a;~this.names.indexOf(c)||this.names.push(c);(this[c]||(this[c]=new e)).a(a,b)};i.prototype.namedItem=function(a){return this[a]instanceof e?this[a]:new e};i.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};i.prototype.item=e.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||h}}document.getItems=function(a){this.__getItemsCACHE__||(this.__getItemsCACHE__={});var a=a||"",b=this.__getItemsCACHE__[a]||(this.__getItemsCACHE__[a]=c("[itemscope]",
this)),g=[],e=(a||"").trim().split(/\s+/);if(e.length>1)for(var f=0,j=e.length;f<j;++f)this.__getItemsCACHE__[e[f]]=b;f=0;for(j=b.length;f<j;++f){var i=b[f],k=i.getAttribute("itemtype");(!a||~e.indexOf(k))&&!i.getAttribute("itemprop")&&(!("itemScope"in i)||i.itemScope)&&g.push(m.fixItemElement(i))}return g};if(b.DocumentFragment&&b.DocumentFragment.prototype)b.DocumentFragment.prototype.getItems=document.getItems;else{var k=function(){var a=k.c.call(d);a.getItems=document.getItems;return a};k.c=document.createDocumentFragment;
document.createDocumentFragment=k}}:function l(c){if(!l.b){var f=c.MicrodataJS;c.DocumentFragment&&c.DocumentFragment.prototype&&(c.DocumentFragment.prototype.getItems=document.getItems);f.fixItemElement=function(c){return c};if(c.PropertyNodeList){if(!("values"in c.PropertyNodeList.prototype))c.PropertyNodeList.prototype.__defineGetter__("values",function(){return this.getValues()}),l.b=!0}else c.addEventListener("DOMContentLoaded",l.bind(c,c),!1),c.addEventListener("load",l.bind(c,c),!1)}})(window,
function(b,c){return window.$$?window.$$(b,c):Array.prototype.slice.apply(c.querySelectorAll(b))},function(b){return window.$A?window.$A(b):Array.prototype.slice.apply(b)});