/* Microdata API polyfill | @version 6.1 | MIT License | github.com/termi */
void function(){
var e=!0,j=null;"use strict";
var k=window,m,n,p={INPUT:j,TEXTAREA:j,PROGRESS:j,METER:j,SELECT:j,OUTPUT:j},q={AUDIO:j,EMBED:j,IFRAME:j,IMG:j,SOURCE:j,TRACK:j,VIDEO:j},r={A:j,AREA:j,LINK:j},t={get:function(){var b=this.nodeName;return this.getAttribute("itemscope")!==j?this:this.getAttribute("itemprop")===j?j:b in p?this.value:"META"===b?this.content:b in q?this.src:b in r?this.href:"OBJECT"===b?this.data:"TIME"===b&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(b){var d=
this.nodeName;if(this.getAttribute("itemprop")===j)throw b=Object.create(DOMException.prototype),b.code=DOMException.INVALID_ACCESS_ERR,b.message="INVALID_ACCESS_ERR: DOM Exception "+b.code,b;return this[d in p?"value":"META"===d?"content":d in q?"src":d in r?"href":"OBJECT"===d?"data":"TIME"===d&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=b}};
function u(b,d){b._||(b._={});var c=b.getAttribute(d),a=b._._mcrdt_||(b._._mcrdt_={}),f=a[d];f?c!==j&&f+""!==c&&f.contains("fake"):f=a[d]=new m(function(){return b.getAttribute(d)},function(){b.setAttribute(d,this+"")},b);return f}var v={get:function(){return u(this,"itemtype")},set:function(b){return this.setAttribute("itemtype",b+""),b}};
function w(b){return Array.from(this.querySelectorAll(b?b.trim().split(/\s+/).map(function(b){return"[itemscope][itemtype~='"+b+"']"}).join(","):"")).filter(function(b){return!b.getAttribute("itemprop")})}var x,y,z=(HTMLDocument||{}).prototype||{},A="getItems"in document;m=k.DOMStringCollection;
n=function(b){function d(a){var b,f=-1,c;if(void 0!==a.length){for(b={items:[]};c=a[++f];)c.getAttribute("itemscope")!==j&&b.items.push(d(c));return b}if(a.getAttribute("itemscope")!==j){b={};if(f=a.getAttribute("itemid"))b.id=f;if(f=a.getAttribute("itemtype"))b.type=f;b.properties=a.properties.toJSON()}return b}if(!x){var c,a=document.createElement("div");try{var f=document.createElement("EMBED");f.itemProp="t";f.itemValue+="1"}catch(g){}A&&z.getItems!=w&&(a.itemScope=e,a.itemType="t","string"==
typeof a.itemType&&(Object.defineProperty(b.Element.prototype,"itemType",v),z.getItems=w));if(A&&!(c=b.PropertyNodeList)){if(!z.getItems.orig){var h=z.getItems;z.getItems=function(){a.innerHTML="<p itemprop='t'>t</p>";a.properties.t[0].innerHTML="t";n(this.defaultView||b);return(this.getItems=h).apply(document,arguments)};z.getItems.orig=h}}else{var i=b.PropertyNodeList;if(!(c=i.prototype).toJSON)c.toJSON=function(){return this.c().map(function(a){a instanceof Element&&(a=d(a));return a})};f=document.createElement("input");
f.itemProp="t";f.itemScope=!1;f.value="1";f.value!=f.itemValue&&(Object.keys(p).forEach(function(a){a="TEXTAREA"==a?"TextArea":a.charAt(0).toUpperCase()+a.substring(1).toLowerCase();(a=b["HTML"+a+"Element"])&&(a=a.prototype)&&Object.defineProperty(a,"itemValue",t)}),c.getValues=function(){for(var a=[],b=-1,f;f=this[++b];)a.push(f.itemValue);return a});c=b.HTMLPropertiesCollection;if(!(c=c.prototype).toJSON)c.toJSON=function(){for(var a={},b=this.names,f=-1,c;c=b[++f];)this[c]instanceof i&&(a[c]=this[c].toJSON());
return a};x=e}}if(!y){if((c=b.DocumentFragment)&&(c=c.prototype))c.getItems||(c.getItems=document.getItems);y=e}};
(!A?function(b){function d(){this.length=0;this.names=[]}function c(){this.length=0;this.values=[]}c.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};c.prototype.getValues=function(){for(var a=[],b=-1,c;c=this[++b];)a.push(c.itemValue);return a};c.prototype.toString=function(){return"[object PropertyNodeList]"};d.prototype.a=function(){for(var a in this)if(this[a]instanceof c||!isNaN(a))this[a]=j,delete this[a];this.length=0;this.names=[]};d.prototype._push=function(a){var b=
a.itemValue,d=a.itemProp,h,i=-1;if(d)for(this[this.length++]=a;h=d[++i];)~this.names.indexOf(h)||this.names.push(h),(this[h]||(this[h]=new c))._push(a,b)};d.prototype.namedItem=function(a){return this[a]instanceof c?this[a]:new c};d.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};d.prototype.item=c.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||j};Object.defineProperties(b.Element.prototype,{itemValue:t,itemProp:{get:function(){return u(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",
a+""),a}},itemScope:{get:function(){return this.getAttribute("itemscope")!==j},set:function(a){a?this.setAttribute("itemscope",""):this.removeAttribute("itemscope");return a}},itemId:{get:function(){var a=(this.getAttribute("itemid")||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+""),a}},itemType:v,itemRef:{get:function(){return u(this,"itemref")},set:function(a){return this.setAttribute("itemref",
a+""),a}},properties:{get:function(){this._||(this._={});var a=this._._mcrdt_||(this._._mcrdt_={}),c=a.b;if(c)if(b.microdata_liveProperties)c.a();else return c;else c=a.b=new d;for(var g=[],a=[],h=[],i,s=-1,l;l=this.childNodes[++s];)1===l.nodeType&&g.push(l);this.getAttribute("itemref")&&(h=this.getAttribute("itemref").trim().split(/\s+/),h.forEach(function(a){(a=document.getElementById(a))&&g.push(a)}));g=g.filter(function(a,b){var c=j,d=a,f=[];if(g.indexOf(a)!==b&&-1!==g.indexOf(a,b))return!1;if(a.id&&
-1!==h.indexOf(a.id))return e;for(;(d=d.parentNode)!==j&&1===d.nodeType;)if(f.push(d),d.getAttribute("itemscope")!==j){c=d;break}return c!==j?-1!==g.indexOf(c)?!1:!f.some(function(a){var b=-1,d=j;if(-1!==(b=g.indexOf(a))){for(a=g[b];(a=a.parentNode)!==j&&1===a.nodeType;)if(a.getAttribute("itemscope")!==j){d=a;break}if(d===c)return e}return!1}):e});for(g.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});i=g.pop();)if(i.getAttribute("itemprop")&&a.push(i),i.getAttribute("itemscope")===
j)for(s=i.childNodes.length;l=i.childNodes[--s];)1===l.nodeType&&g.push(l);a.forEach(c._push.bind(c));return c}}});z.getItems=document.getItems=w;b.PropertyNodeList||(b.PropertyNodeList=c);b.HTMLPropertiesCollection||(b.HTMLPropertiesCollection=d);n(b)}:n)(k);
}();
