/* Microdata API for IE < 8 polyfill | @version 6.1 | MIT License | github.com/termi */
void function(j){
var e=null;
(function(k){if(!("getItems"in document)&&9>(window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||void 0)){var f,i;if((f=window.Node)&&(f=f.prototype)&&f.ielt8)f=document.getElementById("ielt8_style_prev_for_behaviour"),i="",f&&(i=f.getAttribute("data-url")||"",f.id=""),i+=' url("/microdata-js.ielt8.htc") ',f="<style id='ielt8_style_prev_for_behaviour' data-url='"+i+"'>*{behavior: "+i+"}</style>","complete"==document.readyState?document.head.insertAdjacentHTML("beforeend","<br>"+
f):document.write(f);var m,n={INPUT:e,TEXTAREA:e,PROGRESS:e,METER:e,SELECT:e,OUTPUT:e},p={AUDIO:e,EMBED:e,IFRAME:e,IMG:e,SOURCE:e,TRACK:e,VIDEO:e},q={A:e,AREA:e,LINK:e},l=function(a,b){a._||(a._={});var c=a.getAttribute(b,1),d=a._._mcrdt_||(a._._mcrdt_={}),h=d[b];h?c!==e&&h+""!==c&&h.contains("fake"):h=d[b]=new m(function(){return a.getAttribute(b,1)},function(){a.setAttribute(b,this+"",1)},a);return h};f=(HTMLDocument||{}).prototype||{};m=k.DOMStringCollection;var g=function(){this.length=0;this.values=
[]};g.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};g.prototype.getValues=function(){for(var a=[],b=-1,c;c=this[++b];)a.push(c.itemValue);return a};g.prototype.toString=function(){return"[object PropertyNodeList]"};var j=function(){this.length=0;this.names=[]};j.prototype.a=function(){for(var a in this)if(this[a]instanceof g||!isNaN(a))this[a]=e,delete this[a];this.length=0;this.names=[]};j.prototype._push=function(a){var b=a.itemValue,c=a.itemProp,d,h=-1;if(c)for(this[this.length++]=
a;d=c[++h];)~this.names.indexOf(d)||this.names.push(d),(this[d]||(this[d]=new g))._push(a,b)};j.prototype.namedItem=function(a){return this[a]instanceof g?this[a]:new g};j.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};j.prototype.item=g.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||e};var r=function(a){var b,c=-1,d;if(void 0!==a.length){for(b={items:[]};d=a[++c];)d.getAttribute("itemscope",1)!==e&&b.items.push(r(d));return b}if(a.getAttribute("itemscope",1)!==
e){b={};if(c=a.getAttribute("itemid",1))b.id=c;if(c=a.getAttribute("itemtype",1))b.type=c;b.properties=a.properties.toJSON()}return b};g.prototype.toJSON=function(){return this.c().map(function(a){a instanceof Element&&(a=r(a));return a})};j.prototype.toJSON=function(){for(var a={},b=this.names,c=-1,d;d=b[++c];)this[d]instanceof g&&(a[d]=this[d].toJSON());return a};_similar_Object_defineProperties_=function(a,b){var c,d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(c=b[d],"get"in c&&(a["get"+
d]=c.get),"set"in c&&(a["set"+d]=c.set))};_similar_Object_defineProperties_(k.Element.prototype,{itemValue:{get:function(){var a=this.nodeName;return this.getAttribute("itemscope")!==e?this:this.getAttribute("itemprop")===e?e:a in n?this.value:"META"===a?this.content:a in p?this.src:a in q?this.href:"OBJECT"===a?this.data:"TIME"===a&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(a){var b=this.nodeName;if(this.getAttribute("itemprop")===
e)throw a=Object.create(DOMException.prototype),a.code=DOMException.INVALID_ACCESS_ERR,a.message="INVALID_ACCESS_ERR: DOM Exception "+a.code,a;return this[b in n?"value":"META"===b?"content":b in p?"src":b in q?"href":"OBJECT"===b?"data":"TIME"===b&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=a}},itemProp:{get:function(){return l(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",a+"",1),a}},itemScope:{get:function(){return this.getAttribute("itemscope",1)!==e},set:function(a){a?
this.setAttribute("itemscope","",1):this.removeAttribute("itemscope",1);return a}},itemId:{get:function(){var a=(this.getAttribute("itemid",1)||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+"",1),a}},itemType:{get:function(){return l(this,"itemtype")},set:function(a){return this.setAttribute("itemtype",a+""),a}},itemRef:{get:function(){return l(this,"itemref")},set:function(a){return this.setAttribute("itemref",
a+"",1),a}},properties:{get:function(){this._||(this._={});var a=this._._mcrdt_||(this._._mcrdt_={}),b=a.b;if(b)if(k.microdata_liveProperties)b.a();else return b;else b=a.b=new j;for(var c=[],a=[],d=[],h,f=-1,g;g=this.childNodes[++f];)1===g.nodeType&&c.push(g);this.getAttribute("itemref",1)&&(d=this.getAttribute("itemref",1).trim().split(/\s+/),d.forEach(function(a){(a=document.getElementById(a))&&c.push(a)}));c=c.filter(function(a,b){var g=e,f=a,h=[];if(c.indexOf(a)!==b&&-1!==c.indexOf(a,b))return!1;
if(a.id&&-1!==d.indexOf(a.id))return!0;for(;(f=f.parentNode)!==e&&1===f.nodeType;)if(h.push(f),f.getAttribute("itemscope",1)!==e){g=f;break}return g!==e?-1!==c.indexOf(g)?!1:!h.some(function(a){var b=-1,d=e;if(-1!==(b=c.indexOf(a))){for(a=c[b];(a=a.parentNode)!==e&&1===a.nodeType;)if(a.getAttribute("itemscope",1)!==e){d=a;break}if(d===g)return!0}return!1}):!0});for(c.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});h=c.pop();)if(h.getAttribute("itemprop",1)&&a.push(h),h.getAttribute("itemscope",
1)===e)for(f=h.childNodes.length;g=h.childNodes[--f];)1===g.nodeType&&c.push(g);a.forEach(b._push.bind(b));return b}}});f.getItems=document.getItems=function(a){for(var b=this.querySelectorAll("[ITEMSCOPE]"),c=[],a=a&&a.trim().split(/\s+/).map(function(a){return" "+a+" "})||e,d,f=-1,g;d=b[++f];){var j=" "+(d.getAttribute("itemtype")||"")+" ",k,i;i=!(j&&!d.getAttribute("itemprop",1)&&(!("itemScope"in d)||d.itemScope));g=-1;if(a)for(;!i&&(k=a[++g]);)(i=~j.indexOf(k))&&c.push(d);else i||c.push(d)}return c};
k.PropertyNodeList||(k.PropertyNodeList=g);k.HTMLPropertiesCollection||(k.HTMLPropertiesCollection=j)}})(window);
}(window);
