;(function(){
var f=void 0,g=!0,k=null;"use strict";
var l=window,n,o,p={INPUT:f,TEXTAREA:f,PROGRESS:f,METER:f,SELECT:f,OUTPUT:f},q={AUDIO:f,EMBED:f,IFRAME:f,IMG:f,SOURCE:f,TRACK:f,VIDEO:f},r={A:f,AREA:f,LINK:f},t={get:function(){var b=this.nodeName;return this.getAttribute("itemscope")!==k?this:this.getAttribute("itemprop")===k?k:b in p?this.value:"META"===b?this.content:b in q?this.src:b in r?this.href:"OBJECT"===b?this.data:"TIME"===b&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(b){var d=
this.nodeName;if(this.getAttribute("itemprop")===k)throw b=Object.create(DOMException.prototype),b.code=DOMException.INVALID_ACCESS_ERR,b.message="INVALID_ACCESS_ERR: DOM Exception "+b.code,b;return this[d in p?"value":"META"===d?"content":d in q?"src":d in r?"href":"OBJECT"===d?"data":"TIME"===d&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=b}};
function u(b,d){b._||(b._={});var c=b.getAttribute(d),a=b._._mcrdt_||(b._._mcrdt_={}),e=a[d];if(e){if(c!==k&&e+""!==c)try{e.add("")}catch(h){}}else e=a[d]=new n(function(){return b.getAttribute(d)},function(){b.setAttribute(d,this+"")},b);return e}var v={get:function(){return u(this,"itemtype")},set:function(b){return this.setAttribute("itemtype",b+""),b}};function w(b){return this.querySelectorAll(b?b.trim().split(/\s+/).map(function(b){return"[itemscope][itemtype~='"+b+"']"}).join(","):"")}
var x,y,z=(HTMLDocument||{}).prototype||{},A="getItems"in document;n=l.DOMStringCollection;
o=function(b){function d(a){var b,e=-1,c;if(a.length!==f){for(b={items:[]};c=a[++e];)c.getAttribute("itemscope")!==k&&b.items.push(d(c));return b}if(a.getAttribute("itemscope")!==k){b={};if(e=a.getAttribute("itemid"))b.id=e;if(e=a.getAttribute("itemtype"))b.type=e;b.properties=a.properties.toJSON()}return b}if(!x){var c,a=document.createElement("div");try{var e=document.createElement("EMBED");e.itemProp="t";e.itemValue+="1"}catch(h){}A&&z.getItems!=w&&(a.itemScope=g,a.itemType="t","string"==typeof a.itemType&&
(Object.defineProperty(b.Element.prototype,"itemType",v),z.getItems=w));if(A&&!(c=b.PropertyNodeList)){if(!z.getItems.orig){var i=z.getItems;z.getItems=function(){a.innerHTML="<p itemprop='t'>t</p>";a.properties.t[0].innerHTML="t";o(this.defaultView||b);return(this.getItems=i).apply(document,arguments)};z.getItems.orig=i}}else{var j=b.PropertyNodeList;if(!(c=j.prototype).toJSON)c.toJSON=function(){return this.c().map(function(a){a instanceof Element&&(a=d(a));return a})};e=document.createElement("input");
e.itemProp="t";e.itemScope=!1;e.value="1";e.value!=e.itemValue&&(Object.keys(p).forEach(function(a){a=a=="TEXTAREA"?"TextArea":a.charAt(0).toUpperCase()+a.substring(1).toLowerCase();a=b["HTML"+a+"Element"];(a=a.prototype)&&Object.defineProperty(a,"itemValue",t)}),c.getValues=function(){for(var a=[],b=-1,e;e=this[++b];)a.push(e.itemValue);return a});c=b.HTMLPropertiesCollection;if(!(c=c.prototype).toJSON)c.toJSON=function(){for(var a={},b=this.names,e=-1,c;c=b[++e];)this[c]instanceof j&&(a[c]=this[c].toJSON());
return a};x=g}}if(!y){if((c=b.DocumentFragment)&&(c=c.prototype))c.getItems||(c.getItems=document.getItems);y=g}};
(!A?function(b){function d(){this.length=0;this.names=[]}function c(){this.length=0;this.values=[]}c.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};c.prototype.getValues=function(){for(var a=[],b=-1,c;c=this[++b];)a.push(c.itemValue);return a};c.prototype.toString=function(){return"[object PropertyNodeList]"};d.prototype.a=function(){for(var a in this)if(this[a]instanceof c||!isNaN(a))this[a]=k,delete this[a];this.length=0;this.names=[]};d.prototype._push=function(a){var b=
a.itemValue,d=a.itemProp,i,j=-1;if(d)for(this[this.length++]=a;i=d[++j];)~this.names.indexOf(i)||this.names.push(i),(this[i]||(this[i]=new c))._push(a,b)};d.prototype.namedItem=function(a){return this[a]instanceof c?this[a]:new c};d.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};d.prototype.item=c.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||k};Object.defineProperties(b.Element.prototype,{itemValue:t,itemProp:{get:function(){return u(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",
a+""),a}},itemScope:{get:function(){return this.getAttribute("itemscope")!==k},set:function(a){a?this.setAttribute("itemscope",""):this.removeAttribute("itemscope");return a}},itemId:{get:function(){var a=(this.getAttribute("itemid")||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+""),a}},itemType:v,itemRef:{get:function(){return u(this,"itemref")},set:function(a){return this.setAttribute("itemref",
a+""),a}},properties:{get:function(){this._||(this._={});var a=this._._mcrdt_||(this._._mcrdt_={}),c=a.b;if(c)if(b.microdata_liveProperties)c.a();else return c;else c=a.b=new d;for(var h=[],a=[],i=[],j,s=-1,m;m=this.childNodes[++s];)1===m.nodeType&&h.push(m);this.getAttribute("itemref")&&(i=this.getAttribute("itemref").trim().split(/\s+/),i.forEach(function(a){(a=document.getElementById(a))&&h.push(a)}));h=h.filter(function(a,b){var c=k,d=a,e=[];if(h.indexOf(a)!==b&&h.indexOf(a,b)!==-1)return false;
if(a.id&&i.indexOf(a.id)!==-1)return g;for(;(d=d.parentNode)!==k&&d.nodeType===1;){e.push(d);if(d.getAttribute("itemscope")!==k){c=d;break}}return c!==k?h.indexOf(c)!==-1?false:!e.some(function(a){var b=-1,d=k;if((b=h.indexOf(a))!==-1){for(a=h[b];(a=a.parentNode)!==k&&a.nodeType===1;)if(a.getAttribute("itemscope")!==k){d=a;break}if(d===c)return g}return false}):g});for(h.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});j=h.pop();)if(j.getAttribute("itemprop")&&a.push(j),j.getAttribute("itemscope")===
k)for(s=j.childNodes.length;m=j.childNodes[--s];)1===m.nodeType&&h.push(m);a.forEach(c._push.bind(c));return c}}});z.getItems=document.getItems=w;b.PropertyNodeList||(b.PropertyNodeList=c);b.HTMLPropertiesCollection||(b.HTMLPropertiesCollection=d);o(b)}:o)(l);
})();
