/* Microdata API for IE < 8 polyfill | @version 6.0 | MIT License | github.com/termi */
;(function(j){var g=void 0,h=null;if(!("getItems"in document)&&9>(window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||g)){var c,e;if((c=window.Node)&&(c=c.prototype)&&c.ielt8)c=document.getElementById("ielt8_style_prev_for_behaviour"),e="",c&&(e=c.getAttribute("data-url")||"",c.id=""),e+=' url("/microdata-js.ielt8.htc") ',c="<style id='ielt8_style_prev_for_behaviour' data-url='"+e+"'>*{behavior: "+e+"}</style>","complete"==document.readyState?document.head.insertAdjacentHTML("beforeend","<br>"+
c):document.write(c);var n,o={INPUT:g,TEXTAREA:g,PROGRESS:g,METER:g,SELECT:g,OUTPUT:g},p={AUDIO:g,EMBED:g,IFRAME:g,IMG:g,SOURCE:g,TRACK:g,VIDEO:g},q={A:g,AREA:g,LINK:g},m=function(a,b){a._||(a._={});var d=a.getAttribute(b,1),f=a._._mcrdt_||(a._._mcrdt_={}),l=f[b];if(l){if(d!==h&&l+""!==d)try{l.add("")}catch(c){}}else l=f[b]=new n(function(){return a.getAttribute(b,1)},function(){a.setAttribute(b,this+"",1)},a);return l};c=(HTMLDocument||{}).prototype||{};n=j.DOMStringCollection;var i=function(){this.length=
0;this.values=[]};i.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};i.prototype.getValues=function(){for(var a=[],b=-1,d;d=this[++b];)a.push(d.itemValue);return a};i.prototype.toString=function(){return"[object PropertyNodeList]"};var k=function(){this.length=0;this.names=[]};k.prototype.a=function(){for(var a in this)if(this[a]instanceof i||!isNaN(a))this[a]=h,delete this[a];this.length=0;this.names=[]};k.prototype._push=function(a){var b=a.itemValue,d=a.itemProp,f,c=-1;
if(d)for(this[this.length++]=a;f=d[++c];)~this.names.indexOf(f)||this.names.push(f),(this[f]||(this[f]=new i))._push(a,b)};k.prototype.namedItem=function(a){return this[a]instanceof i?this[a]:new i};k.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};k.prototype.item=i.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||h};_similar_Object_defineProperties_=function(a,b){var d,f;for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(d=b[f],"get"in d&&(a["get"+f]=d.get),
"set"in d&&(a["set"+f]=d.set))};_similar_Object_defineProperties_(j.Element.prototype,{itemValue:{get:function(){var a=this.nodeName;return this.getAttribute("itemscope")!==h?this:this.getAttribute("itemprop")===h?h:a in o?this.value:"META"===a?this.content:a in p?this.src:a in q?this.href:"OBJECT"===a?this.data:"TIME"===a&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(a){var b=this.nodeName;if(this.getAttribute("itemprop")===h)throw a=
Object.create(DOMException.prototype),a.code=DOMException.INVALID_ACCESS_ERR,a.message="INVALID_ACCESS_ERR: DOM Exception "+a.code,a;return this[b in o?"value":"META"===b?"content":b in p?"src":b in q?"href":"OBJECT"===b?"data":"TIME"===b&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=a}},itemProp:{get:function(){return m(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",a+"",1),a}},itemScope:{get:function(){return this.getAttribute("itemscope",1)!==h},set:function(a){a?
this.setAttribute("itemscope","",1):this.removeAttribute("itemscope");return a}},itemId:{get:function(){var a=(this.getAttribute("itemid")||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+""),a}},itemType:{get:function(){return m(this,"itemtype")},set:function(a){return this.setAttribute("itemtype",a+""),a}},itemRef:{get:function(){return m(this,"itemref")},set:function(a){return this.setAttribute("itemref",
a+""),a}},properties:{get:function(){this._||(this._={});var a=this._._mcrdt_||(this._._mcrdt_={}),b=a.b;if(b)if(j.microdata_liveProperties)b.a();else return b;else b=a.b=new k;for(var d=[],a=[],f=[],c,i=-1,e;e=this.childNodes[++i];)1===e.nodeType&&d.push(e);this.getAttribute("itemref")&&(f=this.getAttribute("itemref").trim().split(/\s+/),f.forEach(function(a){(a=document.getElementById(a))&&d.push(a)}));d=d.filter(function(a,b){var c=h,e=a,i=[];if(d.indexOf(a)!==b&&d.indexOf(a,b)!==-1)return false;
if(a.id&&f.indexOf(a.id)!==-1)return true;for(;(e=e.parentNode)!==h&&e.nodeType===1;){i.push(e);if(e.getAttribute("itemscope")!==h){c=e;break}}return c!==h?d.indexOf(c)!==-1?false:!i.some(function(a){var b=-1,e=h;if((b=d.indexOf(a))!==-1){for(a=d[b];(a=a.parentNode)!==h&&a.nodeType===1;)if(a.getAttribute("itemscope")!==h){e=a;break}if(e===c)return true}return false}):true});for(d.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});c=d.pop();)if(c.getAttribute("itemprop")&&a.push(c),c.getAttribute("itemscope")===
h)for(i=c.childNodes.length;e=c.childNodes[--i];)1===e.nodeType&&d.push(e);a.forEach(b._push.bind(b));return b}}});c.getItems=document.getItems=function(a){return this.querySelectorAll(a?a.trim().split(/\s+/).map(function(a){return"[itemscope][itemtype~='"+a+"']"}).join(","):"")};j.PropertyNodeList||(j.PropertyNodeList=i);j.HTMLPropertiesCollection||(j.HTMLPropertiesCollection=k)}})(window);
