(function(o,f){"use strict";var g=!0,j=null;function n(a){for(var c=this.querySelectorAll("[itemscope]"),e=[],a=(a||"").trim().split(/\s+/),d,k=-1;d=c[++k];){var b=d.getAttribute("itemtype")||"",q=b.split(/\s+/),p,b=!(b&&!d.getAttribute("itemprop")&&(!("itemScope"in d)||d.itemScope));for(;!b&&(p=q.pop());)(b=~a.indexOf(p))&&e.push(d)}return e}function d(a,c){a._||(a._={});var e=a.getAttribute(c),d=a._._mcrdt_||(a._._mcrdt_={}),b=d[c];b?e!==j&&b+""!==e&&b.update(e):b=d[c]=new i(e,function(){a.setAttribute(c,this+"")});return b}
var i=o.Utils.Dom.DOMStringCollection,b="INPUT,TEXTAREA,PROGRESS,METER,SELECT,OUTPUT".split(","),h="AUDIO,EMBED,IFRAME,IMG,SOURCE,TRACK,VIDEO".split(","),m=["A","AREA","LINK"],e={get:function(){var a=this.nodeName;return this.getAttribute("itemscope")!==j?this:this.getAttribute("itemprop")===j?j:~b.indexOf(a)?this.value:"META"===a?this.content:~h.indexOf(a)?this.src:~m.indexOf(a)?this.href:"OBJECT"===a?this.data:"TIME"===a&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:
this.innerText},set:function(a){var c=this.nodeName;if(this.getAttribute("itemprop")===j)throw a=Object.create(DOMException.prototype),a.code=DOMException.INVALID_ACCESS_ERR,a.message="INVALID_ACCESS_ERR: DOM Exception "+a.code,a;return this[~b.indexOf(c)?"value":"META"===c?"content":~h.indexOf(c)?"src":~m.indexOf(c)?"href":"OBJECT"===c?"data":"TIME"===c&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=a}},k={get:function(){return d(this,"itemtype")},set:function(a){return this.setAttribute("itemtype",
a+"")}};f.c=e;f.b=k;f.e=b;f.a=n;(!document.getItems?function(a){if(!a.PropertyNodeList){var c=a.PropertyNodeList=function(){this.length=0;this.values=[]};c.prototype._push=function(a,c){this[this.length++]=a;this.values.push(c)};c.prototype.namedItem=function(){};c.prototype.values=void 0;c.prototype.getValues=function(){for(var a=[],c=-1,e;e=this[++c];)a.push(e.itemValue);return this.values=a};c.prototype.toString=function(){return"[object PropertyNodeList]"}}if(!a.HTMLPropertiesCollection){var b=
a.HTMLPropertiesCollection=function(){this.length=0;this.names=[]};b.prototype.d=function(){for(var a in this)this[a]instanceof c&&(this[a]=j,delete this[a]);this.length=0;this.names=[]};b.prototype._push=function(a,e,b){this[this.length++]=a;~this.names.indexOf(b)||this.names.push(b);(this[b]||(this[b]=new c))._push(a,e)};b.prototype.namedItem=function(a){return this[a]instanceof c?this[a]:new c};b.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};b.prototype.item=c.prototype.item=
function(a){isNaN(a)&&(a=0);return this[a]||j}}var i=a.HTMLElement&&a.HTMLElement.prototype||a.Element&&a.Element.prototype;i&&Object.defineProperties(i,{itemValue:e,itemProp:{get:function(){return d(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",a)}},itemScope:{get:function(){return this.getAttribute("itemscope")!==j},set:function(a){a?this.setAttribute("itemscope",""):this.removeAttribute("itemscope");return a}},itemId:{get:function(){var a=(this.getAttribute("itemid")||"").trim();
a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+"")}},itemType:k,itemRef:{get:function(){return d(this,"itemref")},set:function(a){return this.setAttribute("itemref",a+"")}},properties:{get:function(){this._||(this._={});var c=this._._mcrdt_||(this._._mcrdt_={}),e=c.f;if(e)if(a.microdata_liveProperties)e.d();else return e;else e=c.f=new b;for(var d=[],c=[],k=[],f,i=-1,h;h=this.childNodes[++i];)1===
h.nodeType&&d.push(h);this.getAttribute("itemref")&&(k=this.getAttribute("itemref").trim().split(/\s+/),k.forEach(function(a){(a=document.getElementById(a))&&d.push(a)}));d=d.filter(function(a,c){var e=j,b=a,f=[];if(d.indexOf(a)!==c&&d.indexOf(a,c)!==-1)return false;if(a.id&&k.indexOf(a.id)!==-1)return g;for(;(b=b.parentNode)!==j&&b.nodeType===1;){f.push(b);if(b.getAttribute("itemscope")!==j){e=b;break}}return e!==j?d.indexOf(e)!==-1?false:!f.some(function(a){var c=-1,b=j;if((c=d.indexOf(a))!==-1){for(a=
d[c];(a=a.parentNode)!==j&&a.nodeType===1;)if(a.getAttribute("itemscope")!==j){b=a;break}if(b===e)return g}return false}):g});for(d.sort(function(a,c){return 3-(c.compareDocumentPosition(a)&6)});f=d.pop();)if(f.getAttribute("itemprop")&&c.push(f),f.getAttribute("itemscope")===j)for(i=f.childNodes.length;h=f.childNodes[--i];)1===h.nodeType&&d.push(h);c.forEach(function(a){i=-1;for(f=a.itemProp;h=f[++i];)e._push(a,a.itemValue,h)});return e}}});try{var h=document.createElement("EMBED");h.itemProp="t";
h.itemValue+="1"}catch(m){}document.getItems=n;f(a)}:f)(o)})(window,function l(f){function n(e){var b,a=-1,c;if(void 0!==e.length){for(b={items:[]};c=e[++a];)c.getAttribute("itemscope")!==j&&b.items.push(n(c));return b}if(e.getAttribute("itemscope")!==j){b={};if(a=e.getAttribute("itemid"))b.id=a;if(a=e.getAttribute("itemtype"))b.type=a;b.properties=e.properties.toJSON()}return b}if(!l.h){var d,i=document.createElement("div"),b=HTMLDocument.prototype;b.getItems!=l.a&&(i.itemScope=g,i.itemType="t",
"string"==typeof i.itemType&&(Object.defineProperty(f.Node.prototype,"itemType",l.b),b.getItems=l.a));if(d=f.PropertyNodeList){var h=f.PropertyNodeList;if(!(d=h.prototype).toJSON)d.toJSON=function(){for(var b=[],d=this.i(),a=-1,c;(c=d[++a])!=j;){c instanceof Element&&(c=n(c));b.push(c)}return b};b=document.createElement("input");b.itemProp="t";b.itemScope=!1;b.value="1";b.value!=b.itemValue&&(l.e.forEach(function(b){b=b=="TEXTAREA"?"TextArea":b.charAt(0).toUpperCase()+b.substring(1).toLowerCase();
b=f["HTML"+b+"Element"];(b=b.prototype)&&Object.defineProperty(b,"itemValue",l.c)}),d.getValues=function(){for(var b=[],d=-1,a;a=this[++d];)b.push(a.itemValue);return b});"values"in d||d.__defineGetter__("values",d.getValues);d=f.HTMLPropertiesCollection;if(!(d=d.prototype).toJSON)d.toJSON=function(){for(var b={},d=this.names,a=-1,c;c=d[++a];)this[c]instanceof h&&(b[c]=this[c].toJSON());return b};l.h=g}else if(!b.getItems.orig){var m=b.getItems;b.getItems=function(){i.innerHTML="<p itemprop='t'>t</p>";
i.properties.t[0].innerHTML="t";l(this.defaultView||f);return(this.getItems=m).apply(document,arguments)};b.getItems.orig=m}}if(!l.g){if((d=f.DocumentFragment)&&(d=d.prototype))d.getItems||(d.getItems=document.getItems);l.g=g}});