(function(k){
var e=null;
function i(d){function h(c){var d,a=-1,b;if(void 0!==c.length){for(d={items:[]};b=c[++a];)b.getAttribute("itemscope")!==e&&d.items.push(h(b));return d}if(c.getAttribute("itemscope")!==e){d={};if(a=c.getAttribute("itemid"))d.id=a;if(a=c.getAttribute("itemtype"))d.type=a;d.properties=c.properties.toJSON()}return d}if(!d.__prot_fix__isfixed){var c;if(c=d.PropertyNodeList){"values"in(c=c.prototype)||c.__defineGetter__("values",function(){return this.getValues()});var g=d.PropertyNodeList;if(!(c=
g.prototype).toJSON)c.toJSON=function(){for(var c=[],d=this.values,a=-1,b;b=d[++a];)b instanceof Element&&(b=h(b)),b&&c.push(b);return c};c=d.HTMLPropertiesCollection;if(!(c=c.prototype).toJSON)c.toJSON=function(){for(var c={},d=this.names,a=-1,b;b=d[++a];)this[b]instanceof g&&(c[b]=this[b].toJSON());return c};i.f=!0}else{var j=HTMLDocument.prototype.getItems;HTMLDocument.prototype.getItems=function(){var c=document.createElement("div");c.innerHTML="<p itemprop='t'>1</p>";c.itemScope=!0;c.properties.t[0].innerHTML=
"2";i(this.defaultView||d);return(this.getItems=j).apply(document,arguments)}}if(!i.d){if((c=d.DocumentFragment)&&(c=c.prototype))c.getItems=document.getItems;i.d=!0}}}(!document.getItems?function(d){var h=d.Utils.Dom.DOMStringCollection;if(!d.PropertyNodeList){var c=d.PropertyNodeList=function(){this.length=0;this.values=[]};c.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};c.prototype.namedItem=function(){};c.prototype.values=void 0;c.prototype.getValues=function(){return this.values};
c.prototype.toString=function(){return"[object PropertyNodeList]"}}if(!d.HTMLPropertiesCollection){var g=d.HTMLPropertiesCollection=function(){this.length=0;this.names=[]};g.prototype.c=function(){for(var a in this)this[a]instanceof c&&(this[a]=e,delete this[a]);this.length=0;this.names=[]};g.prototype._push=function(a,b,d){this[this.length++]=a;~this.names.indexOf(d)||this.names.push(d);(this[d]||(this[d]=new c))._push(a,b)};g.prototype.namedItem=function(a){return this[a]instanceof c?this[a]:new c};
g.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};g.prototype.item=c.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||e}}_throwDOMException=function(){var a=Object.create(DOMException.prototype);a.code=DOMException.INVALID_ACCESS_ERR;a.message="INVALID_ACCESS_ERR: DOM Exception "+a.code;throw a;};var j=d.HTMLElement&&d.HTMLElement.prototype||d.Element&&d.Element.prototype;j&&Object.defineProperties(j,{itemValue:{get:function(){var a=this.nodeName;return this.getAttribute("itemscope")!==
e?this:this.getAttribute("itemprop")===e?e:"META"===a?this.content:~"AUDIO,EMBED,IFRAME,IMG,SOURCE,TRACK,VIDEO".split(",").indexOf(a)?this.src:~["A","AREA","LINK"].indexOf(a)?this.href:"OBJECT"===a?this.data:"TIME"===a&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(a){var b=this.nodeName;this.getAttribute("itemprop")===e&&_throwDOMException();return this["META"===b?"content":~"AUDIO,EMBED,IFRAME,IMG,SOURCE,TRACK,VIDEO".split(",").indexOf(b)?
"src":~["A","AREA","LINK"].indexOf(b)?"href":"OBJECT"===b?"data":"TIME"===b&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=a}},itemProp:{get:function(){var a=this.getAttribute("itemprop"),b=this;b.a?a!==e&&b.a+""!==a&&b.a.update(a):b.a=new h(a,function(){b.setAttribute("itemprop",this+"")});return b.a},set:function(a){return this.setAttribute("itemprop",a)}},itemScope:{get:function(){return this.getAttribute("itemscope")!==e},set:function(a){a?this.setAttribute("itemscope",""):this.removeAttribute("itemscope");
return a}},itemId:{get:function(){var a=(this.getAttribute("itemid")||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+"")}},itemType:{get:function(){return this.getAttribute("itemtype")||""},set:function(a){return this.setAttribute("itemtype",a+"")}},itemRef:{get:function(){var a=this.getAttribute("itemref"),b=this;b.b?a!==e&&b.b+""!==a&&b.b.update(a):b.b=new h(a,function(){b.setAttribute("itemref",
this+"")});return b.b},set:function(a){return this.setAttribute("itemref",a+"")}},properties:{get:function(){var a=this.__properties_CACHE__;if(a)if(d.microdata_liveProperties)a.c();else return a;else a=this.__properties_CACHE__=new g;var b=[],c=[],f=[];Array.from(this.childNodes).forEach(function(a){1===a.nodeType&&b.push(a)});this.getAttribute("itemref")&&(f=this.getAttribute("itemref").trim().split(/\s+/),f.forEach(function(a){(a=document.getElementById(a))&&b.push(a)}));b=b.filter(function(a,
c){var d=e,f=a,g=[];if(b.indexOf(a)!==c&&-1!==b.indexOf(a,c))return!1;for(;(f=f.parentNode)!==e&&1===f.nodeType;)if(g.push(f),f.getAttribute("itemscope")!==e){d=f;break}return d!==e?-1!==b.indexOf(d)?!1:!g.some(function(a){var c=-1,f=e;if(-1!==(c=b.indexOf(a))){for(a=b[c];(a=a.parentNode)!==e&&1===a.nodeType;)if(a.getAttribute("itemscope")!==e){f=a;break}if(f===d)return!0}return!1}):!0});for(b.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});f=b.pop();)f.getAttribute("itemprop")&&c.push(f),
f.getAttribute("itemscope")===e&&(f=Array.from(f.childNodes).reverse(),f.forEach(function(a){1===a.nodeType&&b.push(a)}));c.forEach(function(b){$A(b.itemProp).forEach(a._push.bind(a,b,b.itemValue))});return a}}});try{var l=document.createElement("EMBED");l.e+="123"}catch(k){}document.getItems=function(a){for(var b=!!a,a=(a||"").trim().split(/\s+/),c=Array.from(document.querySelectorAll("[itemscope]",this)),d=[],g=0,i=c.length;g<i;++g){var h=c[g],j=h.getAttribute("itemtype");(!b||~a.indexOf(j))&&!h.getAttribute("itemprop")&&
(!("itemScope"in h)||h.itemScope)&&d.push(h)}return d};i(d)}:i)(k)})(window);